/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RimborsiRouteImport } from './routes/rimborsi'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrezziRouteImport } from './routes/prezzi'
import { Route as PagaRouteImport } from './routes/paga'
import { Route as FontiRouteImport } from './routes/fonti'
import { Route as CercaRouteImport } from './routes/cerca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarIndexRouteImport } from './routes/radar.index'
import { Route as RegiaKeyRouteImport } from './routes/regia.$key'
import { Route as RadarTokenRouteImport } from './routes/radar.$token'
import { Route as GaraSlugRouteImport } from './routes/gara.$slug'
import { Route as GareSettoreSlugRouteImport } from './routes/gare.settore.$slug'
import { Route as GareRegioneSlugRouteImport } from './routes/gare.regione.$slug'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RimborsiRoute = RimborsiRouteImport.update({
  id: '/rimborsi',
  path: '/rimborsi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrezziRoute = PrezziRouteImport.update({
  id: '/prezzi',
  path: '/prezzi',
  getParentRoute: () => rootRouteImport,
} as any)
const PagaRoute = PagaRouteImport.update({
  id: '/paga',
  path: '/paga',
  getParentRoute: () => rootRouteImport,
} as any)
const FontiRoute = FontiRouteImport.update({
  id: '/fonti',
  path: '/fonti',
  getParentRoute: () => rootRouteImport,
} as any)
const CercaRoute = CercaRouteImport.update({
  id: '/cerca',
  path: '/cerca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarIndexRoute = RadarIndexRouteImport.update({
  id: '/radar/',
  path: '/radar/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegiaKeyRoute = RegiaKeyRouteImport.update({
  id: '/regia/$key',
  path: '/regia/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarTokenRoute = RadarTokenRouteImport.update({
  id: '/radar/$token',
  path: '/radar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GaraSlugRoute = GaraSlugRouteImport.update({
  id: '/gara/$slug',
  path: '/gara/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GareSettoreSlugRoute = GareSettoreSlugRouteImport.update({
  id: '/gare/settore/$slug',
  path: '/gare/settore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GareRegioneSlugRoute = GareRegioneSlugRouteImport.update({
  id: '/gare/regione/$slug',
  path: '/gare/regione/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cerca': typeof CercaRoute
  '/fonti': typeof FontiRoute
  '/paga': typeof PagaRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/rimborsi': typeof RimborsiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/gara/$slug': typeof GaraSlugRoute
  '/radar/$token': typeof RadarTokenRoute
  '/regia/$key': typeof RegiaKeyRoute
  '/radar/': typeof RadarIndexRoute
  '/gare/regione/$slug': typeof GareRegioneSlugRoute
  '/gare/settore/$slug': typeof GareSettoreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cerca': typeof CercaRoute
  '/fonti': typeof FontiRoute
  '/paga': typeof PagaRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/rimborsi': typeof RimborsiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/gara/$slug': typeof GaraSlugRoute
  '/radar/$token': typeof RadarTokenRoute
  '/regia/$key': typeof RegiaKeyRoute
  '/radar': typeof RadarIndexRoute
  '/gare/regione/$slug': typeof GareRegioneSlugRoute
  '/gare/settore/$slug': typeof GareSettoreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cerca': typeof CercaRoute
  '/fonti': typeof FontiRoute
  '/paga': typeof PagaRoute
  '/prezzi': typeof PrezziRoute
  '/privacy': typeof PrivacyRoute
  '/rimborsi': typeof RimborsiRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/gara/$slug': typeof GaraSlugRoute
  '/radar/$token': typeof RadarTokenRoute
  '/regia/$key': typeof RegiaKeyRoute
  '/radar/': typeof RadarIndexRoute
  '/gare/regione/$slug': typeof GareRegioneSlugRoute
  '/gare/settore/$slug': typeof GareSettoreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cerca'
    | '/fonti'
    | '/paga'
    | '/prezzi'
    | '/privacy'
    | '/rimborsi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termini'
    | '/gara/$slug'
    | '/radar/$token'
    | '/regia/$key'
    | '/radar/'
    | '/gare/regione/$slug'
    | '/gare/settore/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cerca'
    | '/fonti'
    | '/paga'
    | '/prezzi'
    | '/privacy'
    | '/rimborsi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termini'
    | '/gara/$slug'
    | '/radar/$token'
    | '/regia/$key'
    | '/radar'
    | '/gare/regione/$slug'
    | '/gare/settore/$slug'
  id:
    | '__root__'
    | '/'
    | '/cerca'
    | '/fonti'
    | '/paga'
    | '/prezzi'
    | '/privacy'
    | '/rimborsi'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/termini'
    | '/gara/$slug'
    | '/radar/$token'
    | '/regia/$key'
    | '/radar/'
    | '/gare/regione/$slug'
    | '/gare/settore/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CercaRoute: typeof CercaRoute
  FontiRoute: typeof FontiRoute
  PagaRoute: typeof PagaRoute
  PrezziRoute: typeof PrezziRoute
  PrivacyRoute: typeof PrivacyRoute
  RimborsiRoute: typeof RimborsiRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminiRoute: typeof TerminiRoute
  GaraSlugRoute: typeof GaraSlugRoute
  RadarTokenRoute: typeof RadarTokenRoute
  RegiaKeyRoute: typeof RegiaKeyRoute
  RadarIndexRoute: typeof RadarIndexRoute
  GareRegioneSlugRoute: typeof GareRegioneSlugRoute
  GareSettoreSlugRoute: typeof GareSettoreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rimborsi': {
      id: '/rimborsi'
      path: '/rimborsi'
      fullPath: '/rimborsi'
      preLoaderRoute: typeof RimborsiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prezzi': {
      id: '/prezzi'
      path: '/prezzi'
      fullPath: '/prezzi'
      preLoaderRoute: typeof PrezziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paga': {
      id: '/paga'
      path: '/paga'
      fullPath: '/paga'
      preLoaderRoute: typeof PagaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fonti': {
      id: '/fonti'
      path: '/fonti'
      fullPath: '/fonti'
      preLoaderRoute: typeof FontiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerca': {
      id: '/cerca'
      path: '/cerca'
      fullPath: '/cerca'
      preLoaderRoute: typeof CercaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/': {
      id: '/radar/'
      path: '/radar'
      fullPath: '/radar/'
      preLoaderRoute: typeof RadarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regia/$key': {
      id: '/regia/$key'
      path: '/regia/$key'
      fullPath: '/regia/$key'
      preLoaderRoute: typeof RegiaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar/$token': {
      id: '/radar/$token'
      path: '/radar/$token'
      fullPath: '/radar/$token'
      preLoaderRoute: typeof RadarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gara/$slug': {
      id: '/gara/$slug'
      path: '/gara/$slug'
      fullPath: '/gara/$slug'
      preLoaderRoute: typeof GaraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gare/settore/$slug': {
      id: '/gare/settore/$slug'
      path: '/gare/settore/$slug'
      fullPath: '/gare/settore/$slug'
      preLoaderRoute: typeof GareSettoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gare/regione/$slug': {
      id: '/gare/regione/$slug'
      path: '/gare/regione/$slug'
      fullPath: '/gare/regione/$slug'
      preLoaderRoute: typeof GareRegioneSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CercaRoute: CercaRoute,
  FontiRoute: FontiRoute,
  PagaRoute: PagaRoute,
  PrezziRoute: PrezziRoute,
  PrivacyRoute: PrivacyRoute,
  RimborsiRoute: RimborsiRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminiRoute: TerminiRoute,
  GaraSlugRoute: GaraSlugRoute,
  RadarTokenRoute: RadarTokenRoute,
  RegiaKeyRoute: RegiaKeyRoute,
  RadarIndexRoute: RadarIndexRoute,
  GareRegioneSlugRoute: GareRegioneSlugRoute,
  GareSettoreSlugRoute: GareSettoreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
